version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    depends_on:
      - go-chat
      - python-sentiment
      - rust-auth
      - java-activity

  go-chat:
    build: ./Go-chat
    ports:
      - "8000:8000"

  python-sentiment:
    build: ./python-sentiment
    ports:
      - "5001:5001"

  rust-auth:
    build: ./rust-auth
    ports:
      - "8080:8080"

  java-activity:
    build: ./Java-activity
    ports:
      - "8081:8081"
